Textor/Models/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Textor.Models
{
    public class CommentViewModel
    {
    }
}

Textor/Controllers/A_CommentViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Textor.Models;
using Textor.Entity;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Textor.Repositories;

namespace Textor.Controllers
{
    public class A_CommentViewController : ApplicationController
    {
        public ActionResult commentView()
        {
            return View();
        }

		//ToDo add comment by contexts
		[HttpPost]
		public ActionResult addCommentById(int? translationId, int? requestId, string text)
		{
			if(translationId.HasValue)
			{
				Comment tmpComment = new Comment();
				tmpComment.commentDate = DateTime.Now;
				tmpComment.translationID = translationId.Value;
				tmpComment.text = text;
				tmpComment.userID = User.Identity.GetUserId();
				repository.addComment(tmpComment);

				return RedirectToAction("getCommentsById", new { translationId = translationId.Value });
			}
			else if(requestId.HasValue)
			{
				Comment tmpComment = new Comment();
				tmpComment.commentDate = DateTime.Now;
				tmpComment.requestID = requestId.Value;
				tmpComment.text = text;
				tmpComment.userID = User.Identity.GetUserId();
				repository.addComment(tmpComment);

				return RedirectToAction("getCommentsById", new { requestId = requestId.Value });
			}

			return View("Search");
		}

		[HttpGet]
		public ActionResult getCommentsById(int? translationId, int? requestId)
		{
			if(translationId.HasValue)
			{
				List<A_CommentViewModel> commentList = new List<A_CommentViewModel>();
				var comments = (from c in repository.getComments()
							   where c.translationID == translationId.Value
							   select c);
				if(comments != null)
				{
					foreach(var t in comments)
					{
						A_CommentViewModel commentModel = new A_CommentViewModel();
						commentModel.comment = t.text;
						commentModel.dateCreated = t.commentDate;
						commentModel.mediaName = repository.getMediaById(repository.getTranslationById(translationId.Value).mediaID).name;
						commentModel.userName = (from u in repository.getUsers()
												 where u.Id == t.userID
												 select u).SingleOrDefault().UserName;
						commentList.Add(commentModel);
					}
					CommentViewList results = new CommentViewList();
					results.commentModelList = commentList;
					results.translationId = translationId.Value;
					return View("translationComments", results);
				}
			}
			else if(requestId.HasValue)
			{
				List<A_CommentViewModel> commentList = new List<A_CommentViewModel>();
				var comments = (from c in repository.getComments()
							   where c.requestID == requestId.Value
							   select c);
				if (comments != null)
				{
                    
					foreach (var t in comments)
					{
                        var tmpUser = (from u in repository.getUsers()
                                       where u.Id == t.userID
                                       select u).SingleOrDefault();
                        string name;
                        if (tmpUser == null)
                        {
                            name = "Unknown user";
                        }
                        else
                        {
                            name = tmpUser.UserName;
                        }
						A_CommentViewModel commentModel = new A_CommentViewModel();
						commentModel.comment = t.text;
						commentModel.dateCreated = t.commentDate;
						commentModel.mediaName = repository.getMediaById(repository.getRequestById(requestId.Value).mediaID).name;
                        commentModel.userName = name;
						commentList.Add(commentModel);
					}
					CommentViewList results = new CommentViewList();
					results.commentModelList = commentList;
					results.requestId = requestId.Value;
					return View("requestComments", results);
				}
			}
			return View("Search");
		}
		
    }
}

Textor/Views/A_CommentView/commentView.cshtml
@{Html.RenderAction("getComments");}
@{Html.RenderPartial("postComments");}

Textor/Views/A_CommentView/getComments.cshtml
@model IEnumerable<Textor.Models.A_CommentViewModel>
@{ Layout = null; }
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userAvatarUrl)
        </th>
    </tr>

@if (Model != null) 
{ 
    foreach (var item in Model) 
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.userAvatarUrl)
        </td>
    </tr>
    }
}
else
{
    <tr><td>no Comments</td></tr>
}

</table>

Textor/Views/A_CommentView/postComments.cshtml
@model Textor.Models.A_CommentViewModel


<div class="list-group" style="max-width: 560px;">
    <div id="comments"></div>
    <div id="newcomment">
        <div class="list-group-item">
            <div class="form-horizontal">
                <label class="sr-only" for="CommentText">Comment</label>
                <textarea class="form-control" rows="3" id="CommentText" name="CommentText"></textarea>
                <button type="button" id="btnSave" class="btn btn-primary">Send</button>
            </div>
        </div>
    </div>
</div> 

Textor/Views/A_CommentView/requestComments.cshtml
@model Textor.Models.CommentViewList

@if(Model.commentModelList.Count() != 0)
{
	for(var i = 0; i < Model.commentModelList.Count(); i++)
	{
		<div><p>@Model.commentModelList[i].userName , said: </p></div>
		<div><p>@Model.commentModelList[i].comment</p></div>
		<div><p>at: @Model.commentModelList[i].dateCreated</p></div>
	}
}

<div class="wrapper">

	@using (Html.BeginForm("addComment", "A_CommentView", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		@Html.AntiForgeryToken()
		@Html.ValidationSummary(true)

		<input type="hidden" name="translationId" value="@Model.requestId" />
		<label for="comment">Post a Comment</label>
		<input type="text" name="comment" />

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Submit Comment" class="btn btn-default" />
			</div>
		</div>
	}

</div>

Textor/Views/A_CommentView/translationComments.cshtml
@model Textor.Models.CommentViewList

@if (Model.commentModelList.Count() != 0)
{
	for (var i = 0; i < Model.commentModelList.Count(); i++)
	{
		<div><p>@Model.commentModelList[i].userName , said: </p></div>
		<div><p>@Model.commentModelList[i].comment</p></div>
		<div><p>at: @Model.commentModelList[i].dateCreated</p></div>
	}
}


<div class="wrapper">

	@using (Html.BeginForm("addComment", "A_CommentView", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		@Html.AntiForgeryToken()
		@Html.ValidationSummary(true)
		
		<input type="hidden" name="translationId" value="@Model.translationId" />
		<label for="comment">Post a Comment</label>
		<input type="text" name="comment" />

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Submit Comment" class="btn btn-default" />
			</div>
		</div>
	}

</div>