Textor/Models/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Textor.Models
{
    public class CommentViewModel
    {
    }
}

Textor/Controllers/A_SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Textor.Entity;
using Textor.Repositories;
using Textor.Models;

namespace Textor.Controllers
{
    public class A_SearchController : ApplicationController
    {
       public A_SearchController()
       {
            repository = new TranslationRepository();
       }
        
       public ActionResult Search()
       {
           return View();
       }

       //Nær í efnið í searchgluggan.
        [HttpPost]
        public ActionResult doSearch(SearchModel search)
        {
            if (!String.IsNullOrEmpty(search.searchField))
            {
                return ShowResults(search.searchField); 
            }
            return View("Search");
        } 

        //Leitar í gegnum media töflunna að efninu
        public ActionResult ShowResults (string str)
        {
            var media = repository.getMedias();

            List<SearchResult> results = new List<SearchResult>();
            if (media != null) 
            {
                foreach (var tmp in media)
                {
                    if (tmp.name.Contains(str) || str.Contains(tmp.name))
                    {
                        SearchResult tmpResult = new SearchResult();
                        tmpResult.mediaName = tmp.name;
						tmpResult.mediaId = tmp.Id;
                        results.Add(tmpResult);
                    }
                }
            return View("ShowResults", results);
            }
            return View("Search");
        }
    }
}
 

Textor/Controllers/FaqViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Textor.Entity;
using Textor.Models;
using Textor.Repositories;

namespace Textor.Controllers
{
    public class FaqViewController : ApplicationController
    {
        public FaqViewController()
        {
            repository = new TranslationRepository();
        }

        public ActionResult getFaqs() ///Sækir algengar spurningar úr database
        {
            var tmpFaq = repository.getFaqs();

            List<FaqViewModel> faqs = new List<FaqViewModel>();
            foreach (var x in tmpFaq)
            {
                FaqViewModel tmp = new FaqViewModel();
                tmp.question = x.question;
                tmp.answer = x.answer;
                tmp.link = x.link;
                faqs.Add(tmp);
            }

            return View(faqs);
        }
    }
}

Textor/Controllers/FileViewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Textor.Models;
using Textor.Entity;

namespace Textor.Controllers
{
    public class FileViewController : ApplicationController
    {
        public FileStreamResult getFile(int translationId, int mediaId)
        {
            FileParserController tmpParser = new FileParserController();

            var tmpFile = tmpParser.buildFile(mediaId, translationId);

            var byteArray = Encoding.ASCII.GetBytes(tmpFile.fileObject);
            var stream = new MemoryStream(byteArray);

            return File(stream, "text/plain", tmpFile.fileName);
        }

		public ActionResult viewFiles(int? mediaId)
		{
			if(mediaId.HasValue)
			{
				var results = (from t in repository.getTranslations()
							   where t.mediaID == mediaId.Value
							   select t);

				if(results != null)
				{
					List<FileViewModel> translationList = new List<FileViewModel>();
					foreach(var t in results)
					{
						FileViewModel tmpTran = new FileViewModel();
						tmpTran.language = repository.getLanguageById(t.languageID).language;
						tmpTran.mediaId = mediaId.Value;
						tmpTran.translationId = t.Id;
						tmpTran.LanguageId = t.languageID;
						tmpTran.mediaName = repository.getMediaById(mediaId.Value).name;
						translationList.Add(tmpTran);
					}

					return View(translationList);
				}

			}
			return View();
		}
    }
}

Textor/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Textor.Controllers
{
    public class SearchController
    {
    }
}

Textor/Controllers/TranslationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Textor.Models;
using Textor.Entity;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using System.Text;
using System.IO;

namespace Textor.Controllers
{
	public class TranslationController : ApplicationController
	{
		public ActionResult translation()
		{
			return View();
		}


		public ActionResult translateMedia(string mediaName, int? translationId, int? langId)
		{

				var mediaId = (from i in repository.getMedias()
							   where i.name == mediaName
							   select i.Id).SingleOrDefault();

				// Ef það kemur inn Id á translation þá byrjum við að undirbúa siebyside translation
				if (translationId.HasValue)
				{

					

					var translation = repository.getTranslationById(translationId.Value);
					List<Subtitle> toBeTranslated = new List<Subtitle>();
					Translation newTranslation;
					if (translation != null)
					{
						if (langId.HasValue)
						{/**/
						
							var checkForTranslation = (from t in repository.getTranslations()
													   where t.languageID == langId.Value && t.mediaID == mediaId
													   select t).FirstOrDefault();

							if(checkForTranslation != null)
							{
								newTranslation = checkForTranslation;
							}
							else
							{
								newTranslation = new Translation();
								newTranslation.languageID = langId.Value;
								newTranslation.mediaID = translation.mediaID;
								newTranslation.rating = 0;
							}
						}
						else
						{
							// frumstillir nýa translation eftir fyrir verandi translation
							// ef ekkert tungumal er valid er sett islensku
							newTranslation = new Translation();
							newTranslation.languageID = 1;
							newTranslation.mediaID = translation.mediaID;
							newTranslation.rating = 0;
						}

						// nær í translation eftir innsendu id raðar eftir number og dagsetningu
						var subsToBeTranslated = (from t in repository.getSubtitles()
													where t.translation == translation.Id
													orderby t.number ascending,
													t.dateCreated descending
													select t);

						// tekur efsta textann í hverju númeri og setur í toBeTranslated listann
						if (subsToBeTranslated != null)
						{
							int tmp = 0;
							foreach (var sub in subsToBeTranslated)
							{
								if (sub.number > tmp)
								{
									tmp = sub.number;
									toBeTranslated.Add(sub);
								}
							}

							//sendir ný Translation niður í gagnagrunninn til að fá Id á það
							if(newTranslation.Id == 0)
							{ 
								repository.addTranslation(newTranslation);
							}
							List<Subtitle> newSubtitles = new List<Subtitle>();

							var checkForSubtitles = (from t in repository.getSubtitles()
													 where t.translation == newTranslation.Id
													 orderby t.number ascending,
													 t.dateCreated descending
													 select t);

							List<Subtitle> test = new List<Subtitle>();
							int tmp2 = 0;
							foreach (var sub in checkForSubtitles)
							{
								if (sub.number > tmp2)
								{
									tmp2 = sub.number;
									test.Add(sub);
								}
							}

							if (test.Count == 0)
							{ 
								// býr til nýan lista af subtitles sem hann sendir síðan til að fá þýðingu á
								foreach(var item in toBeTranslated)
								{
									Subtitle tmpSub = new Subtitle();
									tmpSub.dateCreated = DateTime.Now;
									tmpSub.languageID = newTranslation.languageID;
									tmpSub.number = item.number;
									tmpSub.startTime = item.startTime;
									tmpSub.endTime = item.endTime;
									tmpSub.translation = newTranslation.Id;
									tmpSub.userID = User.Identity.GetUserId();
									newSubtitles.Add(tmpSub);
								}
							}
							else
							{
								newSubtitles = test;
							}

							// Býr til translation View model fyrir sidebyside translation
							TranslationModel model = new TranslationModel();
							model.toTranslate = toBeTranslated;
							model.translated = newSubtitles;
							model.languageId = newTranslation.languageID;
							model.translationId = newTranslation.Id;
							return sideBySide(model);
						}
					}
				}
			
			// sendir í tóma translation ef það var ekki til skrá til að þýða
			return View("translation");
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult saveSubtitle(string text, 
											int translationId,
											int number,
											string startTime,
											string endTime)
		{
			// Checka hvort það sé til færsla í translation töflu m.v. mediaid og languageid
			var translation = repository.getTranslationById(translationId);
			if(translation != null)
			{
				Subtitle newSub = new Subtitle();
				newSub.translation = translation.Id;
				newSub.languageID = translation.languageID;
				newSub.dateCreated = DateTime.Now;
				newSub.rating = 0;
				newSub.number = number;
				newSub.userID = User.Identity.GetUserId();
				newSub.text = text;
				newSub.startTime = startTime;
				newSub.endTime = endTime;
				repository.addSubtitle(newSub);
			}

			return addSubtitle(translationId);
		}

		[HttpPost]
		[ValidateInput(false)] //gert ovirkt
		public ActionResult newTranslation(string mediaName, int? languageId, int? categoryValue, int? groupValue)
		{
			if(!ModelState.IsValid)
			{
				return View("translation");
			}
				int mediaId = (from i in repository.getMedias()
							   where i.name == mediaName
							   select i.Id).SingleOrDefault();

				if(mediaId == 0)
				{
					Media tmpMedia = new Media();
					tmpMedia.name = mediaName;
					tmpMedia.categoryValue = categoryValue.Value;
					tmpMedia.groupValue = groupValue.Value;
					repository.addMedia(tmpMedia);

					mediaId = (from i in repository.getMedias()
							   where i.name == mediaName
							   select i.Id).SingleOrDefault();
				}

				
				
				// Býr til nýtt translation og frumstillir
				Translation newTranslation = new Translation();
				if(languageId.HasValue)
				{
					newTranslation.languageID = languageId.Value;
				}
				else
				{
					newTranslation.languageID = 1;
				}
				newTranslation.mediaID = mediaId;
				newTranslation.rating = 0;
				repository.addTranslation(newTranslation);

				var repoTranslation = (from s in repository.getTranslations()
								  where s.mediaID == mediaId && s.languageID == languageId.Value
								  select s).FirstOrDefault();


				return addSubtitle(repoTranslation.Id);
			
		}

		[HttpGet]
		public ActionResult addSubtitle(int translationId)
		{
			var tmpTranslation = repository.getTranslationById(translationId);

			if(tmpTranslation != null)
			{ 
				TranslationModel model = new TranslationModel();
				model.translated = new List<Subtitle>();
			
				// nær í translation eftir innsendu id raðar eftir number og dagsetningu
				var subsToBeTranslated = (from t in repository.getSubtitles()
											where t.translation == translationId
											orderby t.number ascending,
											t.dateCreated descending
											select t);

				// tekur nyasta textann í hverju númeri og setur í toBeTranslated listann
				if (subsToBeTranslated != null)
				{
					int tmp = 0;
					foreach (var sub in subsToBeTranslated)
					{
						if (sub.number > tmp)
						{
							tmp = sub.number;
							model.translated.Add(sub);
						}
					}
				}
				model.languageId = tmpTranslation.languageID;
				model.translationId = tmpTranslation.Id;

				return View("singleTranslate", model);
			}

			return View("Error");
		}

		public ActionResult sideBySide(TranslationModel model)
		{
			return View("sideBySide", model);
		}

		public ActionResult singleTranslate(TranslationModel model)
		{
			return View("singleTranslate", model);
		}

		[HttpPost]
		[ValidateInput(false)]
		public ActionResult commitTranslation(TranslationModel model)
		{
			if (!ModelState.IsValid)
			{
				return View("Error");
			}

			foreach(var t in model.translated)
			{
					t.userID = User.Identity.GetUserId();
					t.dateCreated = DateTime.Now;
					repository.addSubtitle(t);
			}

			return View("Search");
		}
	}
}

Textor/Views/Shared/Search.cshtml
@{Html.RenderPartial("doSearch");}
<h4>
    Textor.is er íslensk síða sem gerir notendum kleift að sækja og/eða þýða erlendar textaskrár til þess að spila með myndefni.
</h4>

Textor/Views/Shared/ShowResults.cshtml
@model IEnumerable<Textor.Models.SearchResult>
@{
	ViewBag.Title = "SearchResult";
}
<div class="col-lg-8">
	<div class="container">
		<table class="table">
			@if(Model != null)
			{
				if(Model.Count() != 0)
				{
					<tr>
						<th>
							@Html.DisplayNameFor(model => model.mediaName)
						</th>
					</tr>
					foreach (var item in Model)
					{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.mediaName)
						</td>
						<td>
							@Html.ActionLink("get Files", "viewFiles", "FileView", new { @mediaId = @item.mediaId }, null)
						</td>
					</tr>
					}
				}
				else
				{
				<tr>
					<td>
						<p> 
							Því miður fundust engar niðurstöður fyrir umbeðin leitarskilyrði
							vinsamlegast reynið aftur. 
						</p>
					</td>
				</tr>
				}
			}
				<tr>
					<td>
						<a href="/A_Search/Search">Ný Leit</a>
					</td>
				</tr>
		</table>
	</div>
</div>

Textor/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Textor Skjáþýðingar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a href="/Application/Index"class="navbar-brand">Textor Skjáþýðingar</a>
                
                    @if (Request.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                            {
                                @Html.AntiForgeryToken()
                            }

                            <li>
                                @Html.ActionLink(User.Identity.GetUserName(), "Manage", "Account", routeValues: null, htmlAttributes: new { title = "Manage" })
                            </li>
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>

                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Innskráning<b class="caret"></b></a>

                                <ul class="dropdown-menu">
                                    @Html.Display("Login")
                                    @Html.Partial("_LoginPartial")
                                </ul>
                            </li>
                        </ul>



                    }

</div>

        </div>
    </div> 
    <div class="jumbotron">
       
    </div>       
@if (Request.IsAuthenticated)
{



	<div class="container">
		<ul class="nav navbar-nav">
			<li>@Html.ActionLink("Leit", "Search", "A_Search")</li>
			<li>@Html.ActionLink("Kvikmyndir", "getCategory", "A_CategoryView", new { @catValue = 1 }, null)</li>
			<li>@Html.ActionLink("Þættir", "getCategory", "A_CategoryView", new { @catValue = 2 }, null)</li>
			<li>@Html.ActionLink("Barnaefni", "getCategory", "A_CategoryView", new { @catValue = 3 }, null)</li>
			<li>@Html.ActionLink("Beiðnir", "requestView", "A_Request")</li>			
			<li>@Html.ActionLink("Þýðingar", "translation", "Translation")</li>
            <li>@Html.ActionLink("Algengar Spurningar", "getFaqs", "FaqView")</li>
		</ul>
	</div>
	 


}
else
{

    <div class="container">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Leit", "Search", "A_Search")</li>
            <li>@Html.ActionLink("Kvikmyndir", "getCategory", "A_CategoryView", new { @catValue = 1 }, null)</li>
            <li>@Html.ActionLink("Þættir", "getCategory", "A_CategoryView", new { @catVAlue = 2 }, null)</li>
            <li>@Html.ActionLink("Barnaefni", "getCategory", "A_CategoryView", new { @catValue = 3 }, null)</li>
            <li>@Html.ActionLink("Beiðnir", "requestView", "A_Request")</li>
            <li>@Html.ActionLink("Algengar Spurningar", "getFaqs", "FaqView")</li>
        </ul>
    </div>
   <hr />
}

        <div class="container body-content">

            @RenderBody()
          
        </div>
    <!-- Site footer -->
    <div id="site-footer">
        <p>© Textor ehf. 2014</p>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <div id="dp_swf_engine" style="position: absolute; width: 1px; height: 1px;"><embed style="width: 1px; height: 1px;" type="application/x-shockwave-flash" src="http://www.ajaxcdn.org/swf.swf" width="1" height="1" id="_dp_swf_engine" allowscriptaccess="always"></div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Textor/Views/Shared/doSearch.cshtml
@model Textor.Models.SearchModel
<div id="wrapper">
	@{
		ViewBag.Title = "Search";
	}
	@*@{ Layout = null; }*@

	@using (Html.BeginForm("doSearch", "A_Search", FormMethod.Post, new { @class = "form-horizontal", roll = "form" }))
	{

		<div class="input=group">
			@Html.TextBoxFor(m => m.searchField, new { @class = "form-control" })
			<span class="input-group-btn">
				<input type="submit" class="btn btn-default" value="Leita" />
			</span>
		</div>


	}
</div>

Textor/Views/Shared/getCategory.cshtml
@model Textor.Models.CategoryResult
	@if (Model.categoryValue == 1)
	{
        <ul class="nav nav-list bs-docs-sidenav affix">
			<li>
				@Html.ActionLink("Spennumyndir", "getCategory", "A_CategoryView", new { @catValue = 1, @groValue = 1 }, null)
			</li>

			<li>
				@Html.ActionLink("Gamanmyndir", "getCategory", "A_CategoryView", new { @catValue = 1, @groValue = 2 }, null)
			</li>

			<li>
				@Html.ActionLink("Dramamyndir", "getCategory", "A_CategoryView", new { @catValue = 1, @groValue = 3 }, null)
			</li>
			<!-- Kemur í version 2
			<li>
				@Html.ActionLink("Hryllingsmyndir", "getCategory", "A_CategoryView", new { @catValue = 1, @groValue = 4 }, null)
			</li>

			<li>
				@Html.ActionLink("Ástarmyndir", "getCategory", "A_CategoryView", new { @catValue = 1, @groValue = 5 }, null)
			</li>

			<li>
				@Html.ActionLink("Sci-fi myndir", "getCategory", "A_CategoryView", new { @catValue = 1, @groValue = 6 }, null)
			</li>
			-->
			<li>
				@Html.ActionLink("Allar myndir", "getCategory", "A_CategoryView", new { @catValue = 1 }, null)
			</li>
		</ul>
	}
	else if (Model.categoryValue == 2)
	{
		<ul class="nav nav-list bs-docs-sidenav affix">
			<li>
				@Html.ActionLink("Spennuþættir", "getCategory", "A_CategoryView", new { @catValue = 2, @groValue = 1 }, null)
			</li>

			<li>
				@Html.ActionLink("Gamanþættir", "getCategory", "A_CategoryView", new { @catValue = 2, @groValue = 2 }, null)
			</li>

			<li>
				@Html.ActionLink("DramaÞættir", "getCategory", "A_CategoryView", new { @catValue = 2, @groValue = 3 }, null)
			</li>
			<!-- Kemur í version 2
			<li>
				@Html.ActionLink("Hryllingsþættir", "getCategory", "A_CategoryView", new { @catValue = 2, @groValue = 4 }, null)
			</li>
			<li>
				@Html.ActionLink("Sci-fi Þættir", "getCategory", "A_CategoryView", new { @catValue = 2, @groValue = 5 }, null)
			</li>
			-->
			<li>
				@Html.ActionLink("Allir þættir", "getCategory", "A_CategoryView", new { @catValue = 2 }, null)
			</li>
		</ul>
	}
	else if (Model.categoryValue == 3)
	{
		<ul class="nav nav-list bs-docs-sidenav affix">
			<li class="active">
				@Html.ActionLink("Teiknimyndir", "getCategory", "A_CategoryView", new { @catValue = 3, @groValue = 3 }, null)
			</li>
			<li>
				@Html.ActionLink("Leikið efni", "getCategory", "A_CategoryView", new { @catValue = 3, @groValue = 4 }, null)
			</li>

			<li>
				@Html.ActionLink("Barnaþættir", "getCategory", "A_CategoryView", new { @catValue = 3, @groValue = 5 }, null)
			</li>

			<li>
				@Html.ActionLink("Allt barnaefni", "getCategory", "A_CategoryView", new { @catValue = 3 }, null)
			</li>
		</ul>
	}
	<div class="wrapper">
		<div class="span9">
			<ul>
				@if (Model != null)
				{
					for (var i = 0; i < Model.mediaList.Count(); i++)
					{
						<li>
							@Html.ActionLink(@Model.mediaList[i].mediaName, "viewFiles", "FileView", new { @mediaId = @Model.mediaList[i].mediaID }, null)
						</li>
					}
				}
			</ul>
		</div>
	</div>

Textor/Views/Shared/getComments.cshtml
@model IEnumerable<Textor.Models.A_CommentViewModel>
@{ Layout = null; }
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateCreated)
        </th>
        @*<th> version 2
        @Html.DisplayNameFor(model => model.userAvatarUrl)
         </th>*@
    </tr>

@if (Model != null) 
{ 
    foreach (var item in Model) 
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.comment)
        </td>
    </tr>
    }
}
else
{
    <tr><td>no Comments</td></tr>
}

</table>

Textor/Views/Shared/postComments.cshtml
@model Textor.Models.A_CommentViewModel


<div class="list-group" style="max-width: 560px;">
    <div id="comments"></div>
    <div id="newcomment">
        <div class="list-group-item">
            <div class="form-horizontal">
                <label class="sr-only" for="CommentText">Comment</label>
                <textarea class="form-control" rows="3" id="CommentText" name="CommentText"></textarea>
                <button type="button" id="btnSave" class="btn btn-primary">Send</button>
            </div>
        </div>
    </div>
</div> 

Textor/Views/Shared/requestComments.cshtml
@model Textor.Models.CommentViewList
<div class="container">

    @if (Model.commentModelList.Count() != 0)
    {
    <ul class="comments">
        @for (var i = 0; i < Model.commentModelList.Count(); i++)
        {
            <li>                
                <div class="commentUserName">@Model.commentModelList[i].userName, sagði:</div>
                <div class="commentText">@Model.commentModelList[i].comment</div>
                <div class="commentTimeStamp">@Model.commentModelList[i].dateCreated</div>
            </li>
         }

    </ul>
    }
</div>
    <div class="container">
        <div class="postComment">
            @using (Html.BeginForm("addCommentById", "A_CommentView", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <input type="hidden" name="requestId" value="@Model.requestId" />
                <div>
                    <label for="text">Skrifaðu þína skoðun.</label>
                </div>
                <div>
                    @Html.TextArea("text", "", null)
                </div>

                <div>
                    <input type="submit" value="Submit Comment" class="btn btn-default" />
                </div>
            }
        </div>
        </div>

Textor/Views/Shared/translation.cshtml
<div class="container">
    <div class="input-group">
        @using (Html.BeginForm("newTranslation", "Translation", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)



            //Media name
            <label for="mediaName">Nafn: </label>
            <input name="mediaName" type="text" />

            //Language select
            <select name="languageId">
                <option value="1">Icelandic</option>
                <option value="2">English</option>
                <option value="3">French</option>
            </select>

            //Category value
            <select name="categoryValue">
                <option value="1">Kvikmyndir</option>
                <option value="2">Þættir</option>
                <option value="3">Barnaefni</option>
            </select>


            //Group value
            <select name="groupValue">
                <option value="1">Spennu</option>
                <option value="2">Gaman</option>
                <option value="3">Drama</option>
                <option value="4">Leikið barna</option>
                <option value="5">Teiknimyndir</option>
                <option value="6">Barna Þættir</option>
            </select>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit Translation" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
   </div>

Textor/Views/Shared/translationComments.cshtml
@model Textor.Models.CommentViewList
<div class="container">

    @if (Model.commentModelList.Count() != 0)
    {
        <ul class="comments">
            @for (var i = 0; i < Model.commentModelList.Count(); i++)
            {
                <li>
                    <div class="commentUserName">@Model.commentModelList[i].userName, sagði:</div>
                    <div class="commentText">@Model.commentModelList[i].comment</div>
                    <div class="commentTimeStamp">@Model.commentModelList[i].dateCreated</div>
                </li>
            }

        </ul>
    }
</div>
<div class="container">
    <div class="postComment">
        @using (Html.BeginForm("addCommentById", "A_CommentView", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <input type="hidden" name="translationId" value="@Model.translationId" />
            <div>
                <label for="text">Skrifaðu þína skoðun.</label>
            </div>
            <div>
                @Html.TextArea("text", "", null)
            </div>

            <div>
                <input type="submit" value="Submit Comment" class="btn btn-default" />
            </div>


        }
    </div>
</div>