Textor/Controllers/A_RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Textor.Models;
using Textor.Entity;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using System.Text;
using System.IO;



namespace Textor.Controllers
{
    public class A_RequestController : ApplicationController
    {

        public ActionResult requestView()
        {
            return View();
        }

        [HttpPost]
        public ActionResult postRequest(A_RequestModel model)
        {
           
            if(!ModelState.IsValid)
            {
                return RedirectToAction("requestView");
            }

            var tmpMed = (from i in repository.getMedias()
                          where i.name == model.mediaName
                          select i).SingleOrDefault();

            if(tmpMed == null)
            {
                tmpMed = new Media();
                tmpMed.name = model.mediaName;
				tmpMed.groupValue = model.groupValue.Value;
				tmpMed.categoryValue = model.categoryValue.Value;
                tmpMed.referenceLink = model.referenceLink;
                repository.addMedia(tmpMed);

                tmpMed = (from i in repository.getMedias()
                          where i.name == model.mediaName
                          select i).SingleOrDefault();
            }

            if(model.File != null)
            {
                model.userId = User.Identity.GetUserId();

				/*
                string joinedUser = User.Identity.Name;
                var getJoinedUserID = from j in repository.getUsers()
                                      where j.UserName == joinedUser
                                      select j.Id;
                model.userId = getJoinedUserID.First().ToString();
				 */

                //model.userId = "kalli bjarna";

                //Guid userGuid = (Guid)Membership.GetUser().ProviderUserKey;
                //model.userId = userGuid.ToString();

                var langId = (from i in repository.getLanguages()
                              where i.language == model.srtLang
                              select i).SingleOrDefault();
                if (langId == null)
                { 
                    Language newLang = new Language();
                    newLang.language = model.srtLang;
                    repository.addLanguageById(newLang);

                    langId = (from i in repository.getLanguages()
                              where i.language == model.srtLang
                              select i).SingleOrDefault();
                }

                FileParserController parser = new FileParserController();
                if (parser.readFile(model.File, model.userId, langId.Id, tmpMed.Id)) 
                {
                    Request tmpReq = new Request();
                    tmpReq.mediaID = tmpMed.Id;
                    tmpReq.rating = 0;
                    repository.addRequest(tmpReq);

                    return RedirectToAction("requestView");
                }

                else
                {
                    return RedirectToAction("requestView"); //invalid file format
                }

            }

            Request tmpRequ = new Request();
            tmpRequ.mediaID = tmpMed.Id;
            tmpRequ.rating = 0;
            repository.addRequest(tmpRequ);

            return RedirectToAction("requestView");

        }

        [HttpGet]
        public ActionResult getRequests()
        {
            var requests = (from r in repository.getRequests()
                            orderby r.Id descending
                            select r);

            if(requests != null)
            {
                List<A_RequestModel> results = new List<A_RequestModel>();
                foreach(var req in requests)
                {
                    A_RequestModel tmp = new A_RequestModel();
					tmp.requestId = req.Id;
                    tmp.mediaName = repository.getMediaById(req.mediaID).name;
                    tmp.rating = req.rating;
					tmp.mediaId = req.mediaID;             

                    results.Add(tmp);
                }

                return View(results);
            }

            return View();
        }

        public FileStreamResult getFile(int? translationId, int? mediaId)
        {
            FileParserController tmpParser = new FileParserController();

            if (translationId != null && mediaId != null) 
            { 
                var tmpFile = tmpParser.buildFile(Convert.ToInt32(translationId) , Convert.ToInt32(mediaId));

                var byteArray = Encoding.ASCII.GetBytes(tmpFile.fileObject);
                var stream = new MemoryStream(byteArray);
                return File(stream, "text/plain", tmpFile.fileName);
            }
            else
            {
                return null;
            }
        }
        
    }
}/// I am God

Textor/Controllers/FileViewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Textor.Models;
using Textor.Entity;

namespace Textor.Controllers
{
    public class FileViewController : ApplicationController
    {
        public FileStreamResult getFile(int translationId, int mediaId)
        {
            FileParserController tmpParser = new FileParserController();

            var tmpFile = tmpParser.buildFile(mediaId, translationId);

            var byteArray = Encoding.ASCII.GetBytes(tmpFile.fileObject);
            var stream = new MemoryStream(byteArray);

            return File(stream, "text/plain", tmpFile.fileName);
        }

		public ActionResult viewFiles(int? mediaId)
		{
			if(mediaId.HasValue)
			{
				var results = (from t in repository.getTranslations()
							   where t.mediaID == mediaId.Value
							   select t);

				if(results != null)
				{
					List<FileViewModel> translationList = new List<FileViewModel>();
					foreach(var t in results)
					{
						FileViewModel tmpTran = new FileViewModel();
						tmpTran.language = repository.getLanguageById(t.languageID).language;
						tmpTran.mediaId = mediaId.Value;
						tmpTran.translationId = t.Id;
						tmpTran.LanguageId = t.languageID;
						tmpTran.mediaName = repository.getMediaById(mediaId.Value).name;
						translationList.Add(tmpTran);
					}

					return View(translationList);
				}

			}
			return View();
		}
    }
}

Textor/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Textor.Controllers
{
    public class RequestController
    {
    }
}

Textor/Views/A_Request/getRequests.cshtml
@model IEnumerable<Textor.Models.A_RequestModel>
@{ Layout = null; }
<div class="container">

	@if (Model != null)
	{
		<table class="table">
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.mediaName)
					</td>
					<!--<td> coming in version 2 soon(tm)
					   @* @Html.DisplayFor(modelItem => item.rating)*@
					</td>-->
					@if (Request.IsAuthenticated)
                    {
					<td>
						@Html.ActionLink("comments", "getCommentsById", "A_CommentView", new { @requestId = @item.requestId }, null)
					</td>
					<td>
						@Html.ActionLink("get Files", "viewFiles", "FileView", new { @mediaId = @item.mediaId }, null)
					</td>
					}
				</tr>
			}
		</table>
	}
	else
	{
		<table class="table">
			<tr><td>No requests available</td></tr>
		</table>
	}
	</div>

Textor/Views/A_Request/postRequest.cshtml
﻿@model Textor.Models.A_RequestModel
<div class="container">

	@using (Html.BeginForm("postRequest", "A_Request", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		@Html.AntiForgeryToken()

		<fieldset>
			<hr />
			@Html.ValidationSummary(true)
            <fieldset>
                <legend>Mynd/myndkeið</legend>
                <div class="input-group">
                    @Html.LabelFor(model => model.mediaName, "Nafn Myndar")
                        @Html.EditorFor(model => model.mediaName)
                        @Html.ValidationMessageFor(model => model.mediaName)
                </div>

                <div class="input-group" >
                    @Html.LabelFor(model => model.referenceLink, "Slóð á mynd eða myndskeið")
                        @Html.EditorFor(model => model.referenceLink)
                        @Html.ValidationMessageFor(model => model.referenceLink)
                </div>
            </fieldset>

            <fieldset>
                <legend>Tegund Myndar/myndskeiðs</legend>
                <label for="categoryValue">Flokkur myndar/myndskeiðs</label>
                <select name="categoryValue">
                    <option value="1">Kvikmyndir</option>
                    <option value="2">Þættir</option>
                    <option value="3">Barnaefni</option>
                </select>
                <br />

                <label for="groupValue">Undiflokkur myndar eða myndskeiðs</label>
                <select name="groupValue">
                    <option value="1">Spennu</option>
                    <option value="2">Gaman</option>
                    <option value="3">Drama</option>
                    <option value="4">Leikið barna</option>
                    <option value="5">Teiknimyndir</option>
                    <option value="6">Barna Þættir</option>
                </select>
            </fieldset>

			@if (Request.IsAuthenticated)
            {
            <fieldset>
                <legend>Sendu inn skrá sem þú villt fá þýdda, ath einungis .srt skrár</legend>
                <div class="fileUploadButton">
                    <input type="file" name="File" />
                    @*@Html.TextBoxFor(model => model.File, new { type = "file" })      *@
                    @*@Html.ValidationMessageFor(model => model.File)                   *@
                </div>                   


    <div class="input-group">
        @Html.LabelFor(model => model.srtLang, "Tungumál sem skráin er á")
        <select name="srtLang">
            <option value="Icelandic">Íslenska</option>
            <option value="English">Enska</option>
            <option value="French">Franska</option>
        </select>
            @*@Html.EditorFor(model => model.srtLang)                   *@
            @*@Html.ValidationMessageFor(model => model.srtLang)        *@
                </div>
            </fieldset>
            }
            <div class="fileUploadButton">
                <input type="submit" value="Búa til beiðni" class="btn btn-default" />
            </div>

		</fieldset>
	}
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

</div>

Textor/Views/A_Request/requestView.cshtml
@{Html.RenderPartial("postRequest");}
@{Html.RenderAction("getRequests", "A_Request");} <!---->